'use client';
import {useEffect,useRef,useState} from 'react';
import type {Property} from '@/lib/properties';
import type {SearchCenter} from '@/lib/radius';
import {pinColor,statusLabel,typeLabel,type TabSettings} from '@/lib/tab-settings';
export const colors=['#157b80','#466eb0','#ad7136'];
export default function ParkMap({properties,selected,onSelect,onOpen,settings,radius}:{settings:TabSettings;properties:Property[],selected:string,onSelect:(p:Property)=>void,onOpen:(p:Property)=>void,radius:{center:SearchCenter;miles:number}|null}){
const el=useRef<HTMLDivElement>(null), map=useRef<any>(null), L=useRef<any>(null),cluster=useRef<any>(null),radiusLayer=useRef<any>(null),markers=useRef<any>({}),baseLayers=useRef<any>({}),callbacks=useRef({onSelect,onOpen});callbacks.current={onSelect,onOpen};const[ready,setReady]=useState(false),[error,setError]=useState(''),[mapStyle,setMapStyle]=useState<'street'|'satellite'>('street');
useEffect(()=>{let cancelled=false;(async()=>{try{const leaflet=await import('leaflet');L.current=leaflet.default||leaflet;(window as any).L=L.current;await import('leaflet.markercluster');if(cancelled||!el.current)return;const l=L.current;map.current=l.map(el.current,{zoomControl:false}).setView([31.1,-99.2],6);l.control.zoom({position:'topright'}).addTo(map.current);baseLayers.current.street=l.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19}).addTo(map.current);baseLayers.current.satellite=l.layerGroup([l.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Tiles © Esri',maxZoom:19}),l.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}',{attribution:'Labels © Esri',maxZoom:19})]);cluster.current=l.markerClusterGroup({showCoverageOnHover:false,maxClusterRadius:45});map.current.addLayer(cluster.current);setReady(true)}catch{setError('Map could not load. Your property list is still available.')}})();return()=>{cancelled=true;map.current?.remove();map.current=null}},[]);
useEffect(()=>{if(!ready)return;const layers=baseLayers.current;for(const key of ['street','satellite'])if(layers[key]&&map.current.hasLayer(layers[key]))map.current.removeLayer(layers[key]);layers[mapStyle]?.addTo(map.current);cluster.current?.bringToFront?.()},[mapStyle,ready]);
useEffect(()=>{if(!ready)return;const l=L.current;cluster.current.clearLayers();markers.current={};const layers:any[]=[];properties.filter(p=>p.latitude!==''&&p.longitude!==''&&p.latitude!=null&&p.longitude!=null).forEach(p=>{const done=['Contacted','Visited'].includes(p.status);const icon=l.divIcon({className:'park-icon',html:`<span style="background:${pinColor(settings,{status:p.status,type:p.type})}" class="pin ${done?'done':''}">${done?'✓':''}</span>`,iconSize:[24,24],iconAnchor:[12,12]});const marker=l.marker([Number(p.latitude),Number(p.longitude)],{icon,title:p.name});const box=document.createElement('div');box.className='park-popup';const title=document.createElement('strong');title.textContent=p.name;box.appendChild(title);for(const value of [typeLabel(settings,p.type),`${p.address}, ${p.city}, TX ${p.zip}`,p.county?`${p.county} County`:'County unverified',statusLabel(settings,p.status),`Last researched: ${p.lastResearched?new Date(p.lastResearched).toLocaleDateString():'Never'}`]){const line=document.createElement('p');line.textContent=value;box.appendChild(line)}const copy=document.createElement('button');copy.textContent=`${p.latitude}, ${p.longitude} ⧉`;copy.onclick=()=>{navigator.clipboard.writeText(`${p.latitude}, ${p.longitude}`).then(()=>copy.textContent='Coordinates copied').catch(()=>copy.textContent='Select coordinates to copy')};box.appendChild(copy);const open=document.createElement('button');open.className='primary';open.textContent='Open complete record';open.onclick=()=>callbacks.current.onOpen(p);box.appendChild(open);marker.bindPopup(box);marker.on('add',()=>marker.getElement()?.setAttribute('aria-label',p.name+' — '+statusLabel(settings,p.status))); marker.on('click',()=>callbacks.current.onSelect(p));markers.current[p.id]=marker;layers.push(marker)});cluster.current.addLayers(layers)},[properties,ready,settings]);
useEffect(()=>{if(!ready||!selected||!markers.current[selected])return;const marker=markers.current[selected];cluster.current.zoomToShowLayer(marker,()=>{map.current.setView(marker.getLatLng(),Math.max(12,map.current.getZoom()));marker.openPopup()})},[selected,ready,properties,settings]);
useEffect(()=>{if(!ready)return;if(radiusLayer.current){map.current.removeLayer(radiusLayer.current);radiusLayer.current=null}if(!radius){map.current.setView([31.1,-99.2],6);return}const center:[number,number]=[radius.center.latitude,radius.center.longitude];const circle=L.current.circle(center,{radius:radius.miles*1609.344,color:'#126f73',fillColor:'#126f73',fillOpacity:0.09,weight:2,interactive:false});const dot=L.current.circleMarker(center,{radius:5,color:'#fff',weight:2,fillColor:'#126f73',fillOpacity:1,interactive:false});radiusLayer.current=L.current.layerGroup([circle,dot]).addTo(map.current);map.current.fitBounds(circle.getBounds(),{padding:[24,24],maxZoom:13})},[radius,ready]);
return <div className="map-wrap"><div ref={el} className="map" aria-label="Interactive Texas property map"/>{error&&<div className="map-error">{error}</div>}<div className="map-tools"><div className="map-style" role="group" aria-label="Map style"><button aria-pressed={mapStyle==='street'} onClick={()=>setMapStyle('street')}>Street</button><button aria-pressed={mapStyle==='satellite'} onClick={()=>setMapStyle('satellite')}>Satellite</button></div><button className="map-reset" onClick={()=>radius&&radiusLayer.current?map.current?.fitBounds(radiusLayer.current.getLayers()[0].getBounds(),{padding:[24,24],maxZoom:13}):map.current?.setView([31.1,-99.2],6)}>{radius?'View search area':'View all Texas'}</button></div><div className="map-legend">{(settings.pinColorBy==='status'?settings.statuses:settings.types).map(t=><span key={t.id}><i style={{background:t.color}}/>{t.label}</span>)}</div></div>}
