'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Plus,Trash2} from 'lucide-react';
import {defaultTabSettings,validateTabSettings,type TabSettings} from '@/lib/tab-settings';
export default function TabSettingsDialog({open,onOpenChange,settings,statusCounts,onSave}:{open:boolean;onOpenChange:(v:boolean)=>void;settings:TabSettings;statusCounts:Record<string,number>;onSave:(value:TabSettings)=>Promise<void>}){
  const [draft,setDraft]=useState(settings),[saving,setSaving]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(open){setDraft(structuredClone(settings));setError('')}},[open,settings]);
  async function save(){setError('');setSaving(true);try{await onSave(validateTabSettings(draft));onOpenChange(false)}catch(e:any){setError(e.message||'Settings could not be saved.')}finally{setSaving(false)}}
  function addStatus(){setDraft(d=>{if(d.statuses.length>=20)return d;let number=1;while(d.statuses.some(tab=>tab.label.toLowerCase()===`new tab ${number}`))number++;return {...d,statuses:[...d.statuses,{id:`custom-${crypto.randomUUID()}`,label:`New tab ${number}`,color:'#6d5bd0'}]}})}
  function restoreDefaults(){setDraft(d=>({...structuredClone(defaultTabSettings),version:d.version,statuses:[...structuredClone(defaultTabSettings.statuses),...d.statuses.filter(tab=>tab.id.startsWith('custom-'))]}))}
  return <Dialog open={open} onOpenChange={v=>{if(!saving)onOpenChange(v)}}><DialogContent className="tab-settings-dialog"><DialogHeader><DialogTitle>Tab & map settings</DialogTitle><DialogDescription>Add or rename status tabs and choose their pin colors. Saved changes apply on all your devices.</DialogDescription></DialogHeader>
  <label className="field"><span>Color map pins by</span><select value={draft.pinColorBy} disabled={saving} onChange={e=>setDraft(d=>({...d,pinColorBy:e.target.value as 'status'|'type'}))}><option value="status">Status tabs</option><option value="type">Property type tabs</option></select></label>
  {(['statuses','types'] as const).map(group=><fieldset key={group} disabled={saving}><legend>{group==='statuses'?'Status tabs':'Property type tabs'}</legend>{draft[group].map((tab,i)=><div className={`tab-setting-row ${group==='statuses'&&tab.id.startsWith('custom-')?'has-remove':''}`} key={tab.id}><label className="field"><span>{tab.id.startsWith('custom-')?'Custom tab':tab.id}</span><input aria-label={'Name for '+tab.id} value={tab.label} maxLength={48} onChange={e=>setDraft(d=>({...d,[group]:d[group].map((v,j)=>j===i?{...v,label:e.target.value}:v)}))}/></label><label className="field color-field"><span>Pin color</span><input aria-label={'Pin color for '+tab.id} type="color" value={tab.color} onChange={e=>setDraft(d=>({...d,[group]:d[group].map((v,j)=>j===i?{...v,color:e.target.value}:v)}))}/></label>{group==='statuses'&&tab.id.startsWith('custom-')&&<button type="button" className="remove-tab" aria-label={`Remove ${tab.label}`} title={statusCounts[tab.id]?`Assigned to ${statusCounts[tab.id]} properties`:'Remove empty tab'} disabled={!!statusCounts[tab.id]} onClick={()=>setDraft(d=>({...d,statuses:d.statuses.filter(value=>value.id!==tab.id)}))}><Trash2 size={16}/></button>}</div>)}{group==='statuses'&&<button type="button" className="secondary add-status-tab" disabled={saving||draft.statuses.length>=20} onClick={addStatus}><Plus size={15}/> Add status tab</button>}</fieldset>)}
  {error&&<p className="settings-error" role="alert">{error}</p>}<div className="settings-actions"><button className="text-button" disabled={saving} onClick={restoreDefaults}>Reset built-in styles</button><button className="secondary" disabled={saving} onClick={()=>onOpenChange(false)}>Cancel</button><button className="primary" disabled={saving} onClick={save}>{saving?'Saving…':'Save settings'}</button></div></DialogContent></Dialog>;
}
