export const types=['RV Park','Mobile Home Park','Mixed RV and Mobile Home Park'];
export const statuses=['Not Contacted','Contacted','Visited','Too Small','Cannot Find Info','New Status'];
export const fields=['id','name','address','city','county','state','zip','type','latitude','longitude','status','notes','lastResearched','source','sourceUrl','verifiedAt','verificationNotes','needsVerification','owner','contactName','phone','email','website','sites','acreage','monthlyRent','yearBuilt','comments','followUp','closed','possibleDuplicate','importId','secondaryType','forSaleStatus','forSalePrice','lastSaleDate','lastSalePrice','originalResearchStatus','importedData'];
export type Property=Record<string,any>;
export const core=['name','address','city','county','state','zip','type','latitude','longitude','source','sourceUrl','verifiedAt'];
export const missing=(p:Property)=>core.some(k=>p[k]===''||p[k]==null);
export function normalize(s:any){return String(s||'').toLowerCase().replace(/\b(street|road|avenue|drive|highway)\b/g,x=>({street:'st',road:'rd',avenue:'ave',drive:'dr',highway:'hwy'}[x]||x)).replace(/[^a-z0-9]/g,'')}
export function duplicate(a:Property,b:Property){if(a.id&&a.id===b.id)return true;const an=normalize(a.name),bn=normalize(b.name);const address=normalize(a.address),other=normalize(b.address);const sameCity=normalize(a.city)===normalize(b.city);const near=a.latitude!==''&&a.longitude!==''&&a.latitude!=null&&a.longitude!=null&&b.latitude!==''&&b.longitude!==''&&b.latitude!=null&&b.longitude!=null&&Math.hypot((Number(a.latitude)-Number(b.latitude))*111,(Number(a.longitude)-Number(b.longitude))*96)<.15;return Boolean((address&&address===other&&sameCity)||(an&&an===bn&&sameCity)||(near)||(sameCity&&an.length>7&&bn.length>7&&(an.includes(bn)||bn.includes(an))))}
export function clean(input:Property,allowedStatuses:string[]=statuses):Property{const p:Property={};for(const k of fields)p[k]=['needsVerification','closed','possibleDuplicate'].includes(k)?(input[k]===true||input[k]==='true'||input[k]===1):String(input[k]??'').trim();for(const k of fields)if(typeof p[k]==='string'&&p[k].length>50000)throw Error(k+' is too long (50,000 characters maximum).');p.state=p.state||'TX';p.status=p.status||statuses[0];if(!p.name)throw Error('Property name is required.');if(!types.includes(p.type))throw Error('Choose a valid property type.');if(!allowedStatuses.includes(p.status))throw Error('Choose a valid research status.');if(p.state!=='TX'&&p.state!=='Texas')throw Error('Only Texas properties can be added.');p.state='TX';if((p.latitude==='')!==(p.longitude===''))throw Error('Enter both latitude and longitude, or leave both blank.');if(p.latitude!==''&&(!Number.isFinite(Number(p.latitude))||!Number.isFinite(Number(p.longitude))||Number(p.latitude)<25||Number(p.latitude)>37||Number(p.longitude)<-107||Number(p.longitude)>-93))throw Error('Coordinates must fall within the Texas region.');for(const k of ['sourceUrl','website'])if(p[k]&&!/^https?:\/\//i.test(p[k]))throw Error(k+' must begin with https:// or http://');for(const k of ['sites','acreage','yearBuilt','forSalePrice','lastSalePrice'])if(p[k]&&(!Number.isFinite(Number(p[k]))||Number(p[k])<0))throw Error(k+' must be a positive number.');for(const k of ['followUp','verifiedAt'])if(p[k]&&!/^\d{4}-\d{2}-\d{2}$/.test(p[k]))throw Error(k+' must use YYYY-MM-DD.');if(p.zip&&!/^\d{5}(-\d{4})?$/.test(p.zip))throw Error('ZIP must contain 5 digits, optionally followed by 4 digits.');if(p.verifiedAt&&(!p.source||!p.sourceUrl))throw Error('Verified records require a data source and source URL.');if(missing(p))p.needsVerification=true;return p;}
export function selectProperties(rows:Property[],q='',type:string|string[]='all',county='all',status:string|string[]='all',quality='all',sort='name'){const query=q.trim().toLowerCase();let a=rows.filter(p=>(!query||[p.name,p.address,p.city,p.county,p.zip,`${p.latitude}, ${p.longitude}`,`${p.latitude},${p.longitude}`].some(s=>String(s).toLowerCase().includes(query)))&&(Array.isArray(type)?!type.length||type.includes(p.type):type==='all'||p.type===type)&&(county==='all'||p.county===county)&&(Array.isArray(status)?!status.length||status.includes(p.status):status==='all'||p.status===status)&&(quality==='all'||quality==='missing'&&missing(p)||quality==='verify'&&p.needsVerification||quality==='closed'&&p.closed||quality==='duplicate'&&p.possibleDuplicate));return a.sort((a,b)=>sort==='recent'?String(b.lastResearched||'').localeCompare(a.lastResearched||''):sort==='oldest'?String(a.lastResearched||'').localeCompare(b.lastResearched||''):String(a[sort]||'').localeCompare(String(b[sort]||''))||a.name.localeCompare(b.name))}
